//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsBiblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRUNTS
    {
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string NOMCLASSE { get; set; }
        public Nullable<System.DateTime> DATEEMPRUNT { get; set; }
        public string Titre { get; set; }
    }
}
