//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsBiblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exemplaire
    {
        public long IdExemplaire { get; set; }
        public Nullable<long> IdPersonne { get; set; }
        public long Isbn { get; set; }
        public string CodeLoc { get; set; }
        public int IdEditeur { get; set; }
        public Nullable<System.DateTime> DateAchat { get; set; }
        public string Etat { get; set; }
        public bool Mediatheque { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
        public Nullable<System.DateTime> DateEmprunt { get; set; }
    }
}
