//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsBiblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class import
    {
        public int idImport { get; set; }
        public string auteur1n { get; set; }
        public string auteur1p { get; set; }
        public string auteur1r { get; set; }
        public string auteur2n { get; set; }
        public string auteur2p { get; set; }
        public string auteur2r { get; set; }
        public string auteur3n { get; set; }
        public string auteur3p { get; set; }
        public string auteur3r { get; set; }
        public string titre { get; set; }
        public string editeurImport { get; set; }
        public string cycleImport { get; set; }
        public Nullable<byte> TomeImport { get; set; }
    }
}
