//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsBiblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIVRE_MEDIA
    {
        public long IDEXEMPLAIRE { get; set; }
        public string rangement { get; set; }
        public string TITRE { get; set; }
        public string NOMAUTEUR { get; set; }
        public string PRENOMAUTEUR { get; set; }
    }
}
