//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibSc.WindowsFormsBiblio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bcdStChristopheEntities1 : DbContext
    {
        public bcdStChristopheEntities1()
            : base("name=bcdStChristopheEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auteur> Auteur { get; set; }
        public virtual DbSet<Classe> Classe { get; set; }
        public virtual DbSet<Editeur> Editeur { get; set; }
        public virtual DbSet<Exemplaire> Exemplaire { get; set; }
        public virtual DbSet<Historique> Historique { get; set; }
        public virtual DbSet<Illustrateur> Illustrateur { get; set; }
        public virtual DbSet<import> import { get; set; }
        public virtual DbSet<Livres> Livres { get; set; }
        public virtual DbSet<Localisation> Localisation { get; set; }
        public virtual DbSet<Motcle> Motcle { get; set; }
        public virtual DbSet<Personne> Personne { get; set; }
        public virtual DbSet<Regles> Regles { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<EMPRUNTS> EMPRUNTS { get; set; }
        public virtual DbSet<LIVRE_MEDIA> LIVRE_MEDIA { get; set; }
        public virtual DbSet<Resum> Resum { get; set; }
    
        [DbFunction("bcdStChristopheEntities1", "fn_resume")]
        public virtual IQueryable<fn_resume_Result> fn_resume(Nullable<long> idExempl)
        {
            var idExemplParameter = idExempl.HasValue ?
                new ObjectParameter("idExempl", idExempl) :
                new ObjectParameter("idExempl", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_resume_Result>("[bcdStChristopheEntities1].[fn_resume](@idExempl)", idExemplParameter);
        }
    }
}
