//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsBiblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regles
    {
        public string NomEcole { get; set; }
        public byte DureeMax { get; set; }
        public byte QunatiteMax { get; set; }
        public string AdresseEcole1 { get; set; }
        public Nullable<int> TelEcole { get; set; }
        public string MailEcole { get; set; }
        public string AdresseEcole2 { get; set; }
    }
}
